/* Generated by Yosys 0.11+50 (git sha1 707d98b06, gcc 11.2.0-7ubuntu2 -fPIC -Os) */

(* \amaranth.hierarchy  = "PCM2PDM" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module PCM2PDM(pcm_strobe_in, pdm_data_out, pdm_clock_out, clk, rst, pcm_data_in);
  reg \$auto$verilog_backend.cc:2082:dump_module$79  = 0;
  (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *)
  wire \$1 ;
  (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *)
  wire \$10 ;
  (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *)
  wire \$12 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:131" *)
  wire \$14 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:134" *)
  wire [6:0] \$16 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:134" *)
  wire [6:0] \$17 ;
  (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *)
  wire \$19 ;
  (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *)
  wire \$21 ;
  (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *)
  wire \$23 ;
  (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *)
  wire \$25 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:137" *)
  wire \$27 ;
  (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *)
  wire \$29 ;
  (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *)
  wire \$3 ;
  (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *)
  wire \$31 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:138" *)
  wire \$33 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:157" *)
  wire [20:0] \$35 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:157" *)
  wire [20:0] \$36 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:127" *)
  wire \$5 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:130" *)
  wire [4:0] \$7 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:130" *)
  wire [4:0] \$8 ;
  (* \amaranth.sample_reg  = 32'd1 *)
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:95" *)
  reg \$sample$s$clock_out$sync$1  = 1'h0;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:95" *)
  wire \$sample$s$clock_out$sync$1$next ;
  (* src = "/home/git/amaranth/amaranth/hdl/ir.py:527" *)
  input clk;
  (* src = "/home/git/amlib/amlib/utils/clockdivider.py:12" *)
  wire clk_divider_clock_enable_in;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:95" *)
  wire clk_divider_clock_out;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:121" *)
  reg [3:0] count1 = 4'h0;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:121" *)
  reg [3:0] \count1$next ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:122" *)
  reg [5:0] count2 = 6'h00;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:122" *)
  reg [5:0] \count2$next ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:22" *)
  wire [17:0] ds_signal_in;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:23" *)
  wire ds_signal_out;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:24" *)
  wire ds_strobe_in;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:25" *)
  wire fir_enable_in;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:26" *)
  reg [17:0] fir_signal_in;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:27" *)
  wire [17:0] fir_signal_out;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:72" *)
  input [17:0] pcm_data_in;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:71" *)
  output pcm_strobe_in;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:69" *)
  output pdm_clock_out;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:70" *)
  output pdm_data_out;
  (* src = "/home/git/amaranth/amaranth/hdl/ir.py:527" *)
  input rst;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:123" *)
  reg strobe0 = 1'h0;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:123" *)
  reg \strobe0$next ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:124" *)
  reg strobe1 = 1'h0;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:124" *)
  reg \strobe1$next ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:125" *)
  reg strobe2 = 1'h0;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:125" *)
  reg \strobe2$next ;
  assign \$10  = ~ (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *) \$sample$s$clock_out$sync$1 ;
  assign \$12  = \$10  & (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *) clk_divider_clock_out;
  assign \$14  = ! (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:131" *) count2;
  assign \$17  = count2 - (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:134" *) 1'h1;
  assign \$1  = ~ (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *) \$sample$s$clock_out$sync$1 ;
  assign \$19  = ~ (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *) \$sample$s$clock_out$sync$1 ;
  assign \$21  = \$19  & (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *) clk_divider_clock_out;
  assign \$23  = ~ (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *) \$sample$s$clock_out$sync$1 ;
  assign \$25  = \$23  & (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *) clk_divider_clock_out;
  assign \$27  = ! (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:137" *) count1;
  assign \$29  = ~ (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *) \$sample$s$clock_out$sync$1 ;
  assign \$31  = \$29  & (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *) clk_divider_clock_out;
  assign \$33  = ! (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:138" *) count2;
  assign \$36  = $signed(fir_signal_out) * (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:157" *) $signed(18'h00004);
  assign \$3  = \$1  & (* src = "/home/git/amaranth/amaranth/hdl/ast.py:1369" *) clk_divider_clock_out;
  assign \$5  = ! (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:127" *) count1;
  assign \$8  = count1 - (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:130" *) 1'h1;
  always @(posedge clk)
    \$sample$s$clock_out$sync$1  <= clk_divider_clock_out;
  always @(posedge clk)
    strobe2 <= \strobe2$next ;
  always @(posedge clk)
    strobe1 <= \strobe1$next ;
  always @(posedge clk)
    strobe0 <= \strobe0$next ;
  always @(posedge clk)
    count2 <= \count2$next ;
  always @(posedge clk)
    count1 <= \count1$next ;
  clk_divider clk_divider (
    .clk(clk),
    .clock_enable_in(1'h1),
    .clock_out(clk_divider_clock_out),
    .rst(rst)
  );
  ds ds (
    .clk(clk),
    .rst(rst),
    .signal_in(ds_signal_in),
    .signal_out(ds_signal_out),
    .strobe_in(ds_strobe_in)
  );
  fir fir (
    .clk(clk),
    .enable_in(fir_enable_in),
    .rst(rst),
    .signal_in(fir_signal_in),
    .signal_out(fir_signal_out)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$79 ) begin end
    \count1$next  = count1;
    (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:126" *)
    casez (\$3 )
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:126" */
      1'h1:
          (* full_case = 32'd1 *)
          (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:127" *)
          casez (\$5 )
            /* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:127" */
            1'h1:
                \count1$next  = 4'hb;
            /* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:129" */
            default:
                \count1$next  = \$8 [3:0];
          endcase
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \count1$next  = 4'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$79 ) begin end
    \count2$next  = count2;
    (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:126" *)
    casez (\$12 )
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:126" */
      1'h1:
          (* full_case = 32'd1 *)
          (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:131" *)
          casez (\$14 )
            /* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:131" */
            1'h1:
                \count2$next  = 6'h2f;
            /* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:133" */
            default:
                \count2$next  = \$17 [5:0];
          endcase
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \count2$next  = 6'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$79 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:126" *)
    casez (\$21 )
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:126" */
      1'h1:
          \strobe0$next  = 1'h1;
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:140" */
      default:
          \strobe0$next  = 1'h0;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \strobe0$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$79 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:126" *)
    casez (\$25 )
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:126" */
      1'h1:
          \strobe1$next  = \$27 ;
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:140" */
      default:
          \strobe1$next  = 1'h0;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \strobe1$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$79 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:126" *)
    casez (\$31 )
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:126" */
      1'h1:
          \strobe2$next  = \$33 ;
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:140" */
      default:
          \strobe2$next  = 1'h0;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \strobe2$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$79 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:147" *)
    casez (strobe2)
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:147" */
      1'h1:
          fir_signal_in = pcm_data_in;
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:149" */
      default:
          fir_signal_in = 18'h00000;
    endcase
  end
  assign \$7  = \$8 ;
  assign \$16  = \$17 ;
  assign \$35  = \$36 ;
  assign \$sample$s$clock_out$sync$1$next  = clk_divider_clock_out;
  assign pdm_data_out = ds_signal_out;
  assign ds_signal_in = \$36 [17:0];
  assign ds_strobe_in = strobe0;
  assign fir_enable_in = strobe1;
  assign pcm_strobe_in = strobe2;
  assign pdm_clock_out = clk_divider_clock_out;
  assign clk_divider_clock_enable_in = 1'h1;
endmodule

(* \amaranth.hierarchy  = "PCM2PDM.clk_divider" *)
(* generator = "Amaranth" *)
module clk_divider(clock_out, rst, clk, clock_enable_in);
  reg \$auto$verilog_backend.cc:2082:dump_module$80  = 0;
  (* src = "/home/git/amlib/amlib/utils/clockdivider.py:20" *)
  wire \$1 ;
  (* src = "/home/git/amlib/amlib/utils/clockdivider.py:22" *)
  wire \$3 ;
  (* src = "/home/git/amlib/amlib/utils/clockdivider.py:20" *)
  wire \$5 ;
  (* src = "/home/git/amlib/amlib/utils/clockdivider.py:29" *)
  wire [4:0] \$7 ;
  (* src = "/home/git/amlib/amlib/utils/clockdivider.py:29" *)
  wire [4:0] \$8 ;
  (* src = "/home/git/amaranth/amaranth/hdl/ir.py:527" *)
  input clk;
  (* src = "/home/git/amlib/amlib/utils/clockdivider.py:18" *)
  reg [3:0] clock_counter = 4'h0;
  (* src = "/home/git/amlib/amlib/utils/clockdivider.py:18" *)
  reg [3:0] \clock_counter$next ;
  (* src = "/home/git/amlib/amlib/utils/clockdivider.py:12" *)
  input clock_enable_in;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:95" *)
  output clock_out;
  reg clock_out = 1'h0;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/pcm2pdm.py:95" *)
  reg \clock_out$next ;
  (* src = "/home/git/amaranth/amaranth/hdl/ir.py:527" *)
  input rst;
  assign \$1  = clock_counter >= (* src = "/home/git/amlib/amlib/utils/clockdivider.py:20" *) 4'hd;
  assign \$3  = ~ (* src = "/home/git/amlib/amlib/utils/clockdivider.py:22" *) clock_out;
  assign \$5  = clock_counter >= (* src = "/home/git/amlib/amlib/utils/clockdivider.py:20" *) 4'hd;
  assign \$8  = clock_counter + (* src = "/home/git/amlib/amlib/utils/clockdivider.py:29" *) 1'h1;
  always @(posedge clk)
    clock_counter <= \clock_counter$next ;
  always @(posedge clk)
    clock_out <= \clock_out$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$80 ) begin end
    \clock_out$next  = clock_out;
    (* src = "/home/git/amlib/amlib/utils/clockdivider.py:20" *)
    casez (\$1 )
      /* src = "/home/git/amlib/amlib/utils/clockdivider.py:20" */
      1'h1:
          (* full_case = 32'd1 *)
          (* src = "/home/git/amlib/amlib/utils/clockdivider.py:21" *)
          casez (clock_enable_in)
            /* src = "/home/git/amlib/amlib/utils/clockdivider.py:21" */
            1'h1:
                \clock_out$next  = \$3 ;
            /* src = "/home/git/amlib/amlib/utils/clockdivider.py:23" */
            default:
                \clock_out$next  = 1'h0;
          endcase
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \clock_out$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$80 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/git/amlib/amlib/utils/clockdivider.py:20" *)
    casez (\$5 )
      /* src = "/home/git/amlib/amlib/utils/clockdivider.py:20" */
      1'h1:
          \clock_counter$next  = 4'h0;
      /* src = "/home/git/amlib/amlib/utils/clockdivider.py:28" */
      default:
          \clock_counter$next  = \$8 [3:0];
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \clock_counter$next  = 4'h0;
    endcase
  end
  assign \$7  = \$8 ;
endmodule

(* \amaranth.hierarchy  = "PCM2PDM.ds" *)
(* generator = "Amaranth" *)
module ds(signal_in, signal_out, rst, clk, strobe_in);
  reg \$auto$verilog_backend.cc:2082:dump_module$81  = 0;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:62" *)
  wire [18:0] \$1 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:67" *)
  wire [18:0] \$10 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:67" *)
  wire [18:0] \$11 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:70" *)
  wire [55:0] \$13 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:70" *)
  wire [18:0] \$14 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:70" *)
  wire [53:0] \$16 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:70" *)
  wire [53:0] \$18 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:62" *)
  wire [18:0] \$2 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:70" *)
  wire [54:0] \$20 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:70" *)
  wire [53:0] \$22 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:70" *)
  wire [53:0] \$24 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:70" *)
  wire [55:0] \$26 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:71" *)
  wire [55:0] \$28 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:71" *)
  wire [18:0] \$29 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:71" *)
  wire [53:0] \$31 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:71" *)
  wire [53:0] \$33 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:71" *)
  wire [54:0] \$35 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:71" *)
  wire [53:0] \$37 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:71" *)
  wire [53:0] \$39 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:65" *)
  wire [18:0] \$4 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:71" *)
  wire [55:0] \$41 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:78" *)
  wire [53:0] \$43 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:78" *)
  wire [53:0] \$44 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:78" *)
  wire [53:0] \$46 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:79" *)
  wire [54:0] \$48 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:79" *)
  wire [53:0] \$49 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:65" *)
  wire [18:0] \$5 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:79" *)
  wire [53:0] \$51 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:79" *)
  wire [54:0] \$53 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:80" *)
  wire [54:0] \$55 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:80" *)
  wire [53:0] \$56 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:80" *)
  wire [53:0] \$58 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:80" *)
  wire [54:0] \$60 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:83" *)
  wire [18:0] \$62 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:83" *)
  wire \$64 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:83" *)
  wire [18:0] \$66 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:83" *)
  wire \$68 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:66" *)
  wire [18:0] \$7 ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:66" *)
  wire [18:0] \$8 ;
  (* src = "/home/git/amaranth/amaranth/hdl/ir.py:527" *)
  input clk;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:59" *)
  reg [17:0] dac;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:48" *)
  reg [17:0] dx0 = 18'h00000;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:48" *)
  reg [17:0] \dx0$next ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:48" *)
  reg [17:0] dx2 = 18'h00000;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:48" *)
  reg [17:0] \dx2$next ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:48" *)
  reg [17:0] dx4 = 18'h00000;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:48" *)
  reg [17:0] \dx4$next ;
  (* src = "/home/git/amaranth/amaranth/hdl/ir.py:527" *)
  input rst;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:55" *)
  wire [17:0] s;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:22" *)
  input [17:0] signal_in;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:23" *)
  output signal_out;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:24" *)
  input strobe_in;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:57" *)
  reg [17:0] v;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:46" *)
  reg [17:0] x0 = 18'h00000;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:46" *)
  reg [17:0] \x0$next ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:46" *)
  reg [17:0] x1 = 18'h00000;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:46" *)
  reg [17:0] \x1$next ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:46" *)
  reg [17:0] x2 = 18'h00000;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:46" *)
  reg [17:0] \x2$next ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:46" *)
  reg [17:0] x3 = 18'h00000;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:46" *)
  reg [17:0] \x3$next ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:46" *)
  reg [17:0] x4 = 18'h00000;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:46" *)
  reg [17:0] \x4$next ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:50" *)
  reg [17:0] xd0 = 18'h00000;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:50" *)
  reg [17:0] \xd0$next ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:50" *)
  reg [17:0] xd1 = 18'h00000;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:50" *)
  reg [17:0] \xd1$next ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:50" *)
  reg [17:0] xd2 = 18'h00000;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:50" *)
  reg [17:0] \xd2$next ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:50" *)
  reg [17:0] xd3 = 18'h00000;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:50" *)
  reg [17:0] \xd3$next ;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:50" *)
  reg [17:0] xd4 = 18'h00000;
  (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:50" *)
  reg [17:0] \xd4$next ;
  assign \$11  = $signed(xd4) + (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:67" *) $signed(dx4);
  assign \$14  = $signed(xd1) + (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:70" *) $signed(x0);
  assign \$16  = $signed(s) * (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:70" *) $signed(36'h000000468);
  assign \$20  = $signed(\$14 ) + (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:70" *) $signed(\$18 );
  assign \$22  = $signed(36'h000000145) * (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:70" *) $signed(x2);
  assign \$26  = $signed(\$20 ) - (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:70" *) $signed(\$24 );
  assign \$2  = $signed(signal_in) - (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:62" *) $signed(dac);
  assign \$29  = $signed(xd3) + (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:71" *) $signed(x2);
  assign \$31  = $signed(s) * (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:71" *) $signed(36'h00000b5f2);
  assign \$35  = $signed(\$29 ) + (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:71" *) $signed(\$33 );
  assign \$37  = $signed(36'h000000399) * (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:71" *) $signed(x4);
  assign \$41  = $signed(\$35 ) - (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:71" *) $signed(\$39 );
  assign \$44  = $signed(s) * (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:78" *) $signed(36'h000000049);
  assign \$49  = $signed(s) * (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:79" *) $signed(36'h000002269);
  assign \$53  = $signed(x1) + (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:79" *) $signed(\$51 );
  assign \$56  = $signed(s) * (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:80" *) $signed(36'h00001f6cb);
  assign \$5  = $signed(xd0) + (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:65" *) $signed(dx0);
  assign \$60  = $signed(x3) + (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:80" *) $signed(\$58 );
  assign \$62  = $signed(signal_in) + (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:83" *) $signed(x4);
  assign \$64  = $signed(\$62 ) >= (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:83" *) $signed(19'h00000);
  assign \$66  = $signed(signal_in) + (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:83" *) $signed(x4);
  assign \$68  = $signed(\$66 ) >= (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:83" *) $signed(19'h00000);
  assign \$8  = $signed(xd2) + (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:66" *) $signed(dx2);
  always @(posedge clk)
    xd4 <= \xd4$next ;
  always @(posedge clk)
    xd3 <= \xd3$next ;
  always @(posedge clk)
    xd2 <= \xd2$next ;
  always @(posedge clk)
    xd1 <= \xd1$next ;
  always @(posedge clk)
    xd0 <= \xd0$next ;
  always @(posedge clk)
    x3 <= \x3$next ;
  always @(posedge clk)
    x1 <= \x1$next ;
  always @(posedge clk)
    x4 <= \x4$next ;
  always @(posedge clk)
    x2 <= \x2$next ;
  always @(posedge clk)
    x0 <= \x0$next ;
  always @(posedge clk)
    dx4 <= \dx4$next ;
  always @(posedge clk)
    dx2 <= \dx2$next ;
  always @(posedge clk)
    dx0 <= \dx0$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$81 ) begin end
    \xd3$next  = xd3;
    (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:74" *)
    casez (strobe_in)
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:74" */
      1'h1:
          \xd3$next  = x3;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \xd3$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$81 ) begin end
    \xd4$next  = xd4;
    (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:74" *)
    casez (strobe_in)
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:74" */
      1'h1:
          \xd4$next  = x4;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \xd4$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$81 ) begin end
    \dx0$next  = dx0;
    (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:74" *)
    casez (strobe_in)
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:74" */
      1'h1:
          \dx0$next  = \$46 [17:0];
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \dx0$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$81 ) begin end
    \dx2$next  = dx2;
    (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:74" *)
    casez (strobe_in)
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:74" */
      1'h1:
          \dx2$next  = \$53 [17:0];
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \dx2$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$81 ) begin end
    \dx4$next  = dx4;
    (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:74" *)
    casez (strobe_in)
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:74" */
      1'h1:
          \dx4$next  = \$60 [17:0];
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \dx4$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$81 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:83" *)
    casez (\$64 )
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:83" */
      1'h1:
          dac = 18'h0ffff;
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:86" */
      default:
          dac = 18'h30001;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$81 ) begin end
    (* full_case = 32'd1 *)
    (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:83" *)
    casez (\$68 )
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:83" */
      1'h1:
          v = 18'h00001;
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:86" */
      default:
          v = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$81 ) begin end
    \x0$next  = \$5 [17:0];
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x0$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$81 ) begin end
    \x2$next  = \$8 [17:0];
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x2$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$81 ) begin end
    \x4$next  = \$11 [17:0];
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x4$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$81 ) begin end
    \x1$next  = \$26 [17:0];
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x1$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$81 ) begin end
    \x3$next  = \$41 [17:0];
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x3$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$81 ) begin end
    \xd0$next  = xd0;
    (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:74" *)
    casez (strobe_in)
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:74" */
      1'h1:
          \xd0$next  = x0;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \xd0$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$81 ) begin end
    \xd1$next  = xd1;
    (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:74" *)
    casez (strobe_in)
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:74" */
      1'h1:
          \xd1$next  = x1;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \xd1$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$81 ) begin end
    \xd2$next  = xd2;
    (* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:74" *)
    casez (strobe_in)
      /* src = "/home/kkojima/pcm2pdm/pcm2pdm/dsord5.py:74" */
      1'h1:
          \xd2$next  = x2;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \xd2$next  = 18'h00000;
    endcase
  end
  assign \$1  = \$2 ;
  assign \$4  = \$5 ;
  assign \$7  = \$8 ;
  assign \$10  = \$11 ;
  assign \$13  = \$26 ;
  assign \$28  = \$41 ;
  assign \$43  = \$46 ;
  assign \$48  = \$53 ;
  assign \$55  = \$60 ;
  assign signal_out = v[0];
  assign s = \$2 [17:0];
  assign \$58  = { \$56 [53], \$56 [53], \$56 [53], \$56 [53], \$56 [53], \$56 [53], \$56 [53], \$56 [53], \$56 [53], \$56 [53], \$56 [53], \$56 [53], \$56 [53], \$56 [53], \$56 [53], \$56 [53], \$56 [53], \$56 [53], \$56 [53:18] };
  assign \$18  = { \$16 [53], \$16 [53], \$16 [53], \$16 [53], \$16 [53], \$16 [53], \$16 [53], \$16 [53], \$16 [53], \$16 [53], \$16 [53], \$16 [53], \$16 [53], \$16 [53], \$16 [53], \$16 [53], \$16 [53], \$16 [53], \$16 [53:18] };
  assign \$24  = { \$22 [53], \$22 [53], \$22 [53], \$22 [53], \$22 [53], \$22 [53], \$22 [53], \$22 [53], \$22 [53], \$22 [53], \$22 [53], \$22 [53], \$22 [53], \$22 [53], \$22 [53], \$22 [53], \$22 [53], \$22 [53], \$22 [53:18] };
  assign \$33  = { \$31 [53], \$31 [53], \$31 [53], \$31 [53], \$31 [53], \$31 [53], \$31 [53], \$31 [53], \$31 [53], \$31 [53], \$31 [53], \$31 [53], \$31 [53], \$31 [53], \$31 [53], \$31 [53], \$31 [53], \$31 [53], \$31 [53:18] };
  assign \$39  = { \$37 [53], \$37 [53], \$37 [53], \$37 [53], \$37 [53], \$37 [53], \$37 [53], \$37 [53], \$37 [53], \$37 [53], \$37 [53], \$37 [53], \$37 [53], \$37 [53], \$37 [53], \$37 [53], \$37 [53], \$37 [53], \$37 [53:18] };
  assign \$46  = { \$44 [53], \$44 [53], \$44 [53], \$44 [53], \$44 [53], \$44 [53], \$44 [53], \$44 [53], \$44 [53], \$44 [53], \$44 [53], \$44 [53], \$44 [53], \$44 [53], \$44 [53], \$44 [53], \$44 [53], \$44 [53], \$44 [53:18] };
  assign \$51  = { \$49 [53], \$49 [53], \$49 [53], \$49 [53], \$49 [53], \$49 [53], \$49 [53], \$49 [53], \$49 [53], \$49 [53], \$49 [53], \$49 [53], \$49 [53], \$49 [53], \$49 [53], \$49 [53], \$49 [53], \$49 [53], \$49 [53:18] };
endmodule

(* \amaranth.hierarchy  = "PCM2PDM.fir" *)
(* generator = "Amaranth" *)
module fir(enable_in, signal_out, rst, clk, signal_in);
  reg \$auto$verilog_backend.cc:2082:dump_module$82  = 0;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:104" *)
  wire \$1 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$10 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$100 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$101 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$102 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$103 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$104 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$105 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$106 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$107 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$108 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$109 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$11 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$110 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$111 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$112 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$113 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:103" *)
  wire [36:0] \$114 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:103" *)
  wire [35:0] \$115 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:103" *)
  wire [35:0] \$117 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:103" *)
  wire [36:0] \$119 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$12 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:104" *)
  wire \$121 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:26" *)
  wire [35:0] \$123 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$13 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$14 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$15 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$16 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$17 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$18 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$19 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$20 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$21 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$22 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$23 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$24 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$25 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$26 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$27 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$28 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$29 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:110" *)
  wire [6:0] \$3 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$30 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$31 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$32 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$33 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$34 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$35 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$36 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$37 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$38 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$39 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:110" *)
  wire [6:0] \$4 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$40 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$41 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$42 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$43 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$44 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$45 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$46 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$47 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$48 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$49 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$50 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$51 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$52 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$53 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$54 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$55 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$56 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$57 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$58 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$59 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:104" *)
  wire \$6 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:104" *)
  wire \$60 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$62 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$63 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$64 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$65 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$66 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$67 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$68 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$69 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$70 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$71 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$72 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$73 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$74 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$75 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$76 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$77 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$78 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$79 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$8 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$80 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$81 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$82 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$83 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$84 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$85 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$86 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$87 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$88 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$89 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
  wire [35:0] \$9 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$90 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$91 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$92 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$93 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$94 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$95 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$96 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$97 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$98 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
  wire [35:0] \$99 ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:88" *)
  reg [17:0] a = 18'h00000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:88" *)
  reg [17:0] \a$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:89" *)
  reg [17:0] b = 18'h00000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:89" *)
  reg [17:0] \b$next ;
  (* src = "/home/git/amaranth/amaranth/hdl/ir.py:527" *)
  input clk;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:25" *)
  input enable_in;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:91" *)
  reg [1:0] fsm_state = 2'h0;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:91" *)
  reg [1:0] \fsm_state$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:86" *)
  reg [5:0] ix = 6'h00;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:86" *)
  reg [5:0] \ix$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:87" *)
  reg [17:0] madd = 18'h00000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:87" *)
  reg [17:0] \madd$next ;
  (* src = "/home/git/amaranth/amaranth/hdl/ir.py:527" *)
  input rst;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:26" *)
  input [17:0] signal_in;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:27" *)
  output [17:0] signal_out;
  reg [17:0] signal_out = 18'h00000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:27" *)
  reg [17:0] \signal_out$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x0 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x0$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x1 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x1$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x10 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x10$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x11 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x11$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x12 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x12$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x13 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x13$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x14 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x14$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x15 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x15$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x16 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x16$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x17 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x17$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x18 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x18$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x19 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x19$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x2 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x2$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x20 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x20$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x21 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x21$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x22 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x22$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x23 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x23$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x24 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x24$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x25 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x25$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x26 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x26$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x27 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x27$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x28 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x28$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x29 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x29$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x3 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x3$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x30 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x30$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x31 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x31$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x32 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x32$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x33 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x33$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x34 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x34$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x35 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x35$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x36 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x36$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x37 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x37$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x38 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x38$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x39 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x39$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x4 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x4$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x40 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x40$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x41 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x41$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x42 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x42$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x43 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x43$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x44 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x44$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x45 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x45$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x46 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x46$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x47 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x47$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x48 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x48$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x49 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x49$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x5 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x5$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x50 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x50$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x6 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x6$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x7 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x7$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x8 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x8$next ;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] x9 = 36'h000000000;
  (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:83" *)
  reg [35:0] \x9$next ;
  assign \$115  = $signed(a) * (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:103" *) $signed(b);
  assign \$119  = $signed(madd) + (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:103" *) $signed(\$117 );
  assign \$121  = ix == (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:104" *) 6'h33;
  assign \$123  = + (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:26" *) $signed(signal_in);
  assign \$1  = ix == (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:104" *) 6'h33;
  assign \$4  = ix + (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:110" *) 1'h1;
  assign \$60  = ix == (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:104" *) 6'h33;
  assign \$6  = ix == (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:104" *) 6'h33;
  always @(posedge clk)
    x0 <= \x0$next ;
  always @(posedge clk)
    x50 <= \x50$next ;
  always @(posedge clk)
    x49 <= \x49$next ;
  always @(posedge clk)
    x48 <= \x48$next ;
  always @(posedge clk)
    x47 <= \x47$next ;
  always @(posedge clk)
    x46 <= \x46$next ;
  always @(posedge clk)
    x45 <= \x45$next ;
  always @(posedge clk)
    x44 <= \x44$next ;
  always @(posedge clk)
    x43 <= \x43$next ;
  always @(posedge clk)
    x42 <= \x42$next ;
  always @(posedge clk)
    x41 <= \x41$next ;
  always @(posedge clk)
    x40 <= \x40$next ;
  always @(posedge clk)
    x39 <= \x39$next ;
  always @(posedge clk)
    x38 <= \x38$next ;
  always @(posedge clk)
    x37 <= \x37$next ;
  always @(posedge clk)
    x36 <= \x36$next ;
  always @(posedge clk)
    x35 <= \x35$next ;
  always @(posedge clk)
    x34 <= \x34$next ;
  always @(posedge clk)
    x33 <= \x33$next ;
  always @(posedge clk)
    x32 <= \x32$next ;
  always @(posedge clk)
    x31 <= \x31$next ;
  always @(posedge clk)
    x30 <= \x30$next ;
  always @(posedge clk)
    x29 <= \x29$next ;
  always @(posedge clk)
    x28 <= \x28$next ;
  always @(posedge clk)
    x27 <= \x27$next ;
  always @(posedge clk)
    x26 <= \x26$next ;
  always @(posedge clk)
    x25 <= \x25$next ;
  always @(posedge clk)
    x24 <= \x24$next ;
  always @(posedge clk)
    x23 <= \x23$next ;
  always @(posedge clk)
    x22 <= \x22$next ;
  always @(posedge clk)
    x21 <= \x21$next ;
  always @(posedge clk)
    x20 <= \x20$next ;
  always @(posedge clk)
    x19 <= \x19$next ;
  always @(posedge clk)
    x18 <= \x18$next ;
  always @(posedge clk)
    x17 <= \x17$next ;
  always @(posedge clk)
    x16 <= \x16$next ;
  always @(posedge clk)
    x15 <= \x15$next ;
  always @(posedge clk)
    x14 <= \x14$next ;
  always @(posedge clk)
    x13 <= \x13$next ;
  always @(posedge clk)
    x12 <= \x12$next ;
  always @(posedge clk)
    x11 <= \x11$next ;
  always @(posedge clk)
    x10 <= \x10$next ;
  always @(posedge clk)
    x9 <= \x9$next ;
  always @(posedge clk)
    x8 <= \x8$next ;
  always @(posedge clk)
    x7 <= \x7$next ;
  always @(posedge clk)
    x6 <= \x6$next ;
  always @(posedge clk)
    x5 <= \x5$next ;
  always @(posedge clk)
    x4 <= \x4$next ;
  always @(posedge clk)
    x3 <= \x3$next ;
  always @(posedge clk)
    x2 <= \x2$next ;
  always @(posedge clk)
    x1 <= \x1$next ;
  always @(posedge clk)
    signal_out <= \signal_out$next ;
  always @(posedge clk)
    fsm_state <= \fsm_state$next ;
  always @(posedge clk)
    madd <= \madd$next ;
  always @(posedge clk)
    b <= \b$next ;
  always @(posedge clk)
    a <= \a$next ;
  always @(posedge clk)
    ix <= \ix$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \ix$next  = ix;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:91" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "IDLE/0" */
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:92" */
      2'h0:
          (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:93" *)
          casez (enable_in)
            /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:93" */
            1'h1:
                \ix$next  = 6'h01;
          endcase
      /* \amaranth.decoding  = "MAC/1" */
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:102" */
      2'h1:
          (* full_case = 32'd1 *)
          (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:104" *)
          casez (\$1 )
            /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:104" */
            1'h1:
                /* empty */;
            /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:106" */
            default:
                \ix$next  = \$4 [5:0];
          endcase
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \ix$next  = 6'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \a$next  = a;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:91" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "IDLE/0" */
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:92" */
      2'h0:
          (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:93" *)
          casez (enable_in)
            /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:93" */
            1'h1:
                \a$next  = x0[17:0];
          endcase
      /* \amaranth.decoding  = "MAC/1" */
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:102" */
      2'h1:
          (* full_case = 32'd1 *)
          (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:104" *)
          casez (\$6 )
            /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:104" */
            1'h1:
                /* empty */;
            /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:106" */
            default:
                (* full_case = 32'd1 *)
                (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:108" *)
                casez (ix)
                  6'h00:
                      \a$next  = x0[17:0];
                  6'h01:
                      \a$next  = x1[17:0];
                  6'h02:
                      \a$next  = x2[17:0];
                  6'h03:
                      \a$next  = x3[17:0];
                  6'h04:
                      \a$next  = x4[17:0];
                  6'h05:
                      \a$next  = x5[17:0];
                  6'h06:
                      \a$next  = x6[17:0];
                  6'h07:
                      \a$next  = x7[17:0];
                  6'h08:
                      \a$next  = x8[17:0];
                  6'h09:
                      \a$next  = x9[17:0];
                  6'h0a:
                      \a$next  = x10[17:0];
                  6'h0b:
                      \a$next  = x11[17:0];
                  6'h0c:
                      \a$next  = x12[17:0];
                  6'h0d:
                      \a$next  = x13[17:0];
                  6'h0e:
                      \a$next  = x14[17:0];
                  6'h0f:
                      \a$next  = x15[17:0];
                  6'h10:
                      \a$next  = x16[17:0];
                  6'h11:
                      \a$next  = x17[17:0];
                  6'h12:
                      \a$next  = x18[17:0];
                  6'h13:
                      \a$next  = x19[17:0];
                  6'h14:
                      \a$next  = x20[17:0];
                  6'h15:
                      \a$next  = x21[17:0];
                  6'h16:
                      \a$next  = x22[17:0];
                  6'h17:
                      \a$next  = x23[17:0];
                  6'h18:
                      \a$next  = x24[17:0];
                  6'h19:
                      \a$next  = x25[17:0];
                  6'h1a:
                      \a$next  = x26[17:0];
                  6'h1b:
                      \a$next  = x27[17:0];
                  6'h1c:
                      \a$next  = x28[17:0];
                  6'h1d:
                      \a$next  = x29[17:0];
                  6'h1e:
                      \a$next  = x30[17:0];
                  6'h1f:
                      \a$next  = x31[17:0];
                  6'h20:
                      \a$next  = x32[17:0];
                  6'h21:
                      \a$next  = x33[17:0];
                  6'h22:
                      \a$next  = x34[17:0];
                  6'h23:
                      \a$next  = x35[17:0];
                  6'h24:
                      \a$next  = x36[17:0];
                  6'h25:
                      \a$next  = x37[17:0];
                  6'h26:
                      \a$next  = x38[17:0];
                  6'h27:
                      \a$next  = x39[17:0];
                  6'h28:
                      \a$next  = x40[17:0];
                  6'h29:
                      \a$next  = x41[17:0];
                  6'h2a:
                      \a$next  = x42[17:0];
                  6'h2b:
                      \a$next  = x43[17:0];
                  6'h2c:
                      \a$next  = x44[17:0];
                  6'h2d:
                      \a$next  = x45[17:0];
                  6'h2e:
                      \a$next  = x46[17:0];
                  6'h2f:
                      \a$next  = x47[17:0];
                  6'h30:
                      \a$next  = x48[17:0];
                  6'h31:
                      \a$next  = x49[17:0];
                  6'h??:
                      \a$next  = x50[17:0];
                endcase
          endcase
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \a$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x5$next  = x5;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x5$next  = x4;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x5$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x6$next  = x6;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x6$next  = x5;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x6$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x7$next  = x7;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x7$next  = x6;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x7$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x8$next  = x8;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x8$next  = x7;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x8$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x9$next  = x9;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x9$next  = x8;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x9$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x10$next  = x10;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x10$next  = x9;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x10$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x11$next  = x11;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x11$next  = x10;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x11$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x12$next  = x12;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x12$next  = x11;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x12$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x13$next  = x13;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x13$next  = x12;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x13$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x14$next  = x14;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x14$next  = x13;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x14$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \b$next  = b;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:91" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "IDLE/0" */
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:92" */
      2'h0:
          (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:93" *)
          casez (enable_in)
            /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:93" */
            1'h1:
                \b$next  = 18'h000a4;
          endcase
      /* \amaranth.decoding  = "MAC/1" */
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:102" */
      2'h1:
          (* full_case = 32'd1 *)
          (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:104" *)
          casez (\$60 )
            /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:104" */
            1'h1:
                /* empty */;
            /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:106" */
            default:
                (* full_case = 32'd1 *)
                (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:109" *)
                casez (ix)
                  6'h00:
                      \b$next  = 18'h000a4;
                  6'h01:
                      \b$next  = 18'h000da;
                  6'h02:
                      \b$next  = 18'h00163;
                  6'h03:
                      \b$next  = 18'h0021b;
                  6'h04:
                      \b$next  = 18'h00309;
                  6'h05:
                      \b$next  = 18'h00436;
                  6'h06:
                      \b$next  = 18'h005a6;
                  6'h07:
                      \b$next  = 18'h0075f;
                  6'h08:
                      \b$next  = 18'h00962;
                  6'h09:
                      \b$next  = 18'h00bb0;
                  6'h0a:
                      \b$next  = 18'h00e47;
                  6'h0b:
                      \b$next  = 18'h01121;
                  6'h0c:
                      \b$next  = 18'h01436;
                  6'h0d:
                      \b$next  = 18'h0177b;
                  6'h0e:
                      \b$next  = 18'h01ae3;
                  6'h0f:
                      \b$next  = 18'h01e5c;
                  6'h10:
                      \b$next  = 18'h021d6;
                  6'h11:
                      \b$next  = 18'h0253d;
                  6'h12:
                      \b$next  = 18'h0287c;
                  6'h13:
                      \b$next  = 18'h02b7e;
                  6'h14:
                      \b$next  = 18'h02e31;
                  6'h15:
                      \b$next  = 18'h03083;
                  6'h16:
                      \b$next  = 18'h03262;
                  6'h17:
                      \b$next  = 18'h033c2;
                  6'h18:
                      \b$next  = 18'h0349a;
                  6'h19:
                      \b$next  = 18'h034e2;
                  6'h1a:
                      \b$next  = 18'h0349a;
                  6'h1b:
                      \b$next  = 18'h033c2;
                  6'h1c:
                      \b$next  = 18'h03262;
                  6'h1d:
                      \b$next  = 18'h03083;
                  6'h1e:
                      \b$next  = 18'h02e31;
                  6'h1f:
                      \b$next  = 18'h02b7e;
                  6'h20:
                      \b$next  = 18'h0287c;
                  6'h21:
                      \b$next  = 18'h0253d;
                  6'h22:
                      \b$next  = 18'h021d6;
                  6'h23:
                      \b$next  = 18'h01e5c;
                  6'h24:
                      \b$next  = 18'h01ae3;
                  6'h25:
                      \b$next  = 18'h0177b;
                  6'h26:
                      \b$next  = 18'h01436;
                  6'h27:
                      \b$next  = 18'h01121;
                  6'h28:
                      \b$next  = 18'h00e47;
                  6'h29:
                      \b$next  = 18'h00bb0;
                  6'h2a:
                      \b$next  = 18'h00962;
                  6'h2b:
                      \b$next  = 18'h0075f;
                  6'h2c:
                      \b$next  = 18'h005a6;
                  6'h2d:
                      \b$next  = 18'h00436;
                  6'h2e:
                      \b$next  = 18'h00309;
                  6'h2f:
                      \b$next  = 18'h0021b;
                  6'h30:
                      \b$next  = 18'h00163;
                  6'h31:
                      \b$next  = 18'h000da;
                  6'h??:
                      \b$next  = 18'h000a4;
                endcase
          endcase
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \b$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x15$next  = x15;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x15$next  = x14;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x15$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x16$next  = x16;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x16$next  = x15;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x16$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x17$next  = x17;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x17$next  = x16;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x17$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x18$next  = x18;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x18$next  = x17;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x18$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x19$next  = x19;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x19$next  = x18;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x19$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x20$next  = x20;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x20$next  = x19;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x20$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x21$next  = x21;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x21$next  = x20;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x21$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x22$next  = x22;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x22$next  = x21;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x22$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x23$next  = x23;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x23$next  = x22;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x23$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x24$next  = x24;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x24$next  = x23;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x24$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \madd$next  = madd;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:91" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "IDLE/0" */
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:92" */
      2'h0:
          (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:93" *)
          casez (enable_in)
            /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:93" */
            1'h1:
                \madd$next  = 18'h00000;
          endcase
      /* \amaranth.decoding  = "MAC/1" */
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:102" */
      2'h1:
          \madd$next  = \$119 [17:0];
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \madd$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x25$next  = x25;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x25$next  = x24;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x25$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x26$next  = x26;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x26$next  = x25;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x26$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x27$next  = x27;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x27$next  = x26;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x27$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x28$next  = x28;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x28$next  = x27;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x28$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x29$next  = x29;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x29$next  = x28;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x29$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x30$next  = x30;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x30$next  = x29;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x30$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x31$next  = x31;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x31$next  = x30;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x31$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x32$next  = x32;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x32$next  = x31;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x32$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x33$next  = x33;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x33$next  = x32;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x33$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x34$next  = x34;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x34$next  = x33;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x34$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \fsm_state$next  = fsm_state;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:91" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "IDLE/0" */
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:92" */
      2'h0:
          (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:93" *)
          casez (enable_in)
            /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:93" */
            1'h1:
                \fsm_state$next  = 2'h1;
          endcase
      /* \amaranth.decoding  = "MAC/1" */
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:102" */
      2'h1:
          (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:104" *)
          casez (\$121 )
            /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:104" */
            1'h1:
                \fsm_state$next  = 2'h2;
          endcase
      /* \amaranth.decoding  = "OUTPUT/2" */
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:113" */
      2'h2:
          \fsm_state$next  = 2'h0;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \fsm_state$next  = 2'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x35$next  = x35;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x35$next  = x34;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x35$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x36$next  = x36;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x36$next  = x35;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x36$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x37$next  = x37;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x37$next  = x36;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x37$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x38$next  = x38;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x38$next  = x37;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x38$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x39$next  = x39;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x39$next  = x38;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x39$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x40$next  = x40;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x40$next  = x39;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x40$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x41$next  = x41;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x41$next  = x40;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x41$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x42$next  = x42;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x42$next  = x41;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x42$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x43$next  = x43;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x43$next  = x42;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x43$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x44$next  = x44;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x44$next  = x43;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x44$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \signal_out$next  = signal_out;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:91" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "IDLE/0" */
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:92" */
      2'h0:
          /* empty */;
      /* \amaranth.decoding  = "MAC/1" */
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:102" */
      2'h1:
          /* empty */;
      /* \amaranth.decoding  = "OUTPUT/2" */
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:113" */
      2'h2:
          \signal_out$next  = madd;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \signal_out$next  = 18'h00000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x45$next  = x45;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x45$next  = x44;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x45$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x46$next  = x46;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x46$next  = x45;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x46$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x47$next  = x47;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x47$next  = x46;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x47$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x48$next  = x48;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x48$next  = x47;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x48$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x49$next  = x49;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x49$next  = x48;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x49$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x50$next  = x50;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x50$next  = x49;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x50$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x0$next  = x0;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x0$next  = \$123 ;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x0$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x1$next  = x1;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x1$next  = x0;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x1$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x2$next  = x2;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x2$next  = x1;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x2$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x3$next  = x3;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x3$next  = x2;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x3$next  = 36'h000000000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2082:dump_module$82 ) begin end
    \x4$next  = x4;
    (* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" *)
    casez (enable_in)
      /* src = "/home/git/amlib/amlib/dsp/fixedpointfirfilter.py:121" */
      1'h1:
          \x4$next  = x3;
    endcase
    (* src = "/home/git/amaranth/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \x4$next  = 36'h000000000;
    endcase
  end
  assign \$3  = \$4 ;
  assign \$9  = x0;
  assign \$10  = x1;
  assign \$11  = x2;
  assign \$12  = x3;
  assign \$13  = x4;
  assign \$14  = x5;
  assign \$15  = x6;
  assign \$16  = x7;
  assign \$17  = x8;
  assign \$18  = x9;
  assign \$19  = x10;
  assign \$20  = x11;
  assign \$21  = x12;
  assign \$22  = x13;
  assign \$23  = x14;
  assign \$24  = x15;
  assign \$25  = x16;
  assign \$26  = x17;
  assign \$27  = x18;
  assign \$28  = x19;
  assign \$29  = x20;
  assign \$30  = x21;
  assign \$31  = x22;
  assign \$32  = x23;
  assign \$33  = x24;
  assign \$34  = x25;
  assign \$35  = x26;
  assign \$36  = x27;
  assign \$37  = x28;
  assign \$38  = x29;
  assign \$39  = x30;
  assign \$40  = x31;
  assign \$41  = x32;
  assign \$42  = x33;
  assign \$43  = x34;
  assign \$44  = x35;
  assign \$45  = x36;
  assign \$46  = x37;
  assign \$47  = x38;
  assign \$48  = x39;
  assign \$49  = x40;
  assign \$50  = x41;
  assign \$51  = x42;
  assign \$52  = x43;
  assign \$53  = x44;
  assign \$54  = x45;
  assign \$55  = x46;
  assign \$56  = x47;
  assign \$57  = x48;
  assign \$58  = x49;
  assign \$59  = x50;
  assign \$63  = 36'h0000000a4;
  assign \$64  = 36'h0000000da;
  assign \$65  = 36'h000000163;
  assign \$66  = 36'h00000021b;
  assign \$67  = 36'h000000309;
  assign \$68  = 36'h000000436;
  assign \$69  = 36'h0000005a6;
  assign \$70  = 36'h00000075f;
  assign \$71  = 36'h000000962;
  assign \$72  = 36'h000000bb0;
  assign \$73  = 36'h000000e47;
  assign \$74  = 36'h000001121;
  assign \$75  = 36'h000001436;
  assign \$76  = 36'h00000177b;
  assign \$77  = 36'h000001ae3;
  assign \$78  = 36'h000001e5c;
  assign \$79  = 36'h0000021d6;
  assign \$80  = 36'h00000253d;
  assign \$81  = 36'h00000287c;
  assign \$82  = 36'h000002b7e;
  assign \$83  = 36'h000002e31;
  assign \$84  = 36'h000003083;
  assign \$85  = 36'h000003262;
  assign \$86  = 36'h0000033c2;
  assign \$87  = 36'h00000349a;
  assign \$88  = 36'h0000034e2;
  assign \$89  = 36'h00000349a;
  assign \$90  = 36'h0000033c2;
  assign \$91  = 36'h000003262;
  assign \$92  = 36'h000003083;
  assign \$93  = 36'h000002e31;
  assign \$94  = 36'h000002b7e;
  assign \$95  = 36'h00000287c;
  assign \$96  = 36'h00000253d;
  assign \$97  = 36'h0000021d6;
  assign \$98  = 36'h000001e5c;
  assign \$99  = 36'h000001ae3;
  assign \$100  = 36'h00000177b;
  assign \$101  = 36'h000001436;
  assign \$102  = 36'h000001121;
  assign \$103  = 36'h000000e47;
  assign \$104  = 36'h000000bb0;
  assign \$105  = 36'h000000962;
  assign \$106  = 36'h00000075f;
  assign \$107  = 36'h0000005a6;
  assign \$108  = 36'h000000436;
  assign \$109  = 36'h000000309;
  assign \$110  = 36'h00000021b;
  assign \$111  = 36'h000000163;
  assign \$112  = 36'h0000000da;
  assign \$113  = 36'h0000000a4;
  assign \$114  = \$119 ;
  assign \$117  = { \$115 [35], \$115 [35], \$115 [35], \$115 [35], \$115 [35], \$115 [35], \$115 [35], \$115 [35], \$115 [35], \$115 [35], \$115 [35], \$115 [35], \$115 [35], \$115 [35], \$115 [35], \$115 [35], \$115 [35], \$115 [35], \$115 [35:18] };
endmodule

